In [1]:
import numpy as np
import pandas as pd

## DataTypes and Attributes 
Numpy's main datatype is ndarray.

In [4]:
a1 = np.array([1,2,3])
a2 = np.array([[1.3, 2, 5],
              [3,5.9, 3]])
a3 = np.array([[[1,2,3],
               [4,5,6,],
               [7,8,9]],
               [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])


In [5]:
a1

array([1, 2, 3])

In [6]:
a2

array([[1.3, 2. , 5. ],
       [3. , 5.9, 3. ]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [9]:
a1.shape


(3,)

In [10]:
a2.shape


(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
# Create a dataframe from numpy array

df = pd.DataFrame(a2)
df


0    1    2
0  1.3  2.0  5.0
1  3.0  5.9  3.0


# 2. Creating Numpy Arrays

In [14]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [21]:
a3.shape

(2, 3, 3)

In [22]:
ones = np.ones((2, 3, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [27]:
# Usecase would be using this as a placeholder. Sort of an initial state
zeros = np.zeros((2,3), dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [49]:
range_array = np.arange(2, 100, 10)
range_array

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [55]:
a3.size

18

In [88]:
np.random.seed(0)
random_array = np.random.randint(0,4, size=(2,4))
random_array

array([[0, 3, 1, 0],
       [3, 3, 3, 3]])

In [90]:
random_array.shape

(2, 4)

In [72]:
# generate a 1 by 3 array with 3 different upper bounds
upper_bounds = np.random.randint(1, [2,3,4])
upper_bounds

array([1, 1, 3])

In [96]:
# generate a 1 by 3 array with 3 different lower bounds
lower_bounds = np.random.randint([2,3,4], 10)
lower_bounds

array([8, 3, 6])

In [93]:
# generate a 2 by 4 array using broadcasting
two_by_four = np.random.randint([1, 3, 5, 7], [[8], [9]])
two_by_four

array([[7, 3, 6, 7],
       [6, 4, 6, 7]])

In [113]:
np.random.seed(0)
random_array_2 = np.random.random((5,4))
random_array_2

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675, 0.87001215]])

In [114]:
random_array_2.shape

(5, 4)

## 3. Viewing Array and matrices

In [128]:
np.random.seed(0)
random_array_3 = np.random.randint(10, size= (5,3))
random_array_3

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [134]:
np.unique(random_array_3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
random_array_4 = np.random.randint(10, size=(2,2,3,4,5))
random_array_4

array([[[[[2, 1, 6, 9, 2],
          [3, 4, 9, 9, 7],
          [2, 0, 1, 6, 8],
          [7, 9, 7, 1, 3]],

         [[2, 7, 2, 8, 7],
          [6, 3, 5, 0, 4],
          [5, 9, 6, 5, 1],
          [6, 5, 0, 8, 8]],

         [[3, 7, 5, 2, 9],
          [5, 0, 4, 9, 6],
          [2, 6, 1, 4, 7],
          [3, 7, 0, 5, 2]]],


        [[[8, 9, 5, 0, 6],
          [0, 1, 3, 4, 6],
          [0, 7, 4, 3, 3],
          [3, 2, 1, 3, 8]],

         [[1, 9, 8, 8, 4],
          [6, 3, 6, 9, 5],
          [8, 9, 0, 7, 6],
          [4, 8, 4, 5, 5]],

         [[6, 7, 3, 8, 9],
          [1, 1, 8, 1, 9],
          [4, 8, 9, 3, 1],
          [6, 4, 9, 9, 5]]]],



       [[[[0, 7, 6, 6, 7],
          [2, 1, 1, 5, 9],
          [2, 1, 9, 1, 4],
          [0, 3, 9, 6, 5]],

         [[5, 4, 7, 5, 1],
          [2, 2, 1, 1, 1],
          [9, 4, 8, 9, 2],
          [5, 7, 1, 1, 7]],

         [[0, 1, 6, 8, 6],
          [7, 7, 2, 5, 4],
          [2, 1, 9, 6, 3],
          [4, 5, 6, 3, 7]]],


  

In [142]:
random_array_4.shape, random_array_4.ndim

((2, 2, 3, 4, 5), 5)

In [148]:
random_array_4[:, :, :1, :3, :1]

array([[[[[2],
          [3],
          [2]]],


        [[[8],
          [0],
          [0]]]],



       [[[[0],
          [2],
          [2]]],


        [[[8],
          [7],
          [4]]]]])

## 4. Manipulating and Comparing Arrays
Minipulations and finding patterns happens here. This is the fun part of machine learning

### Learning some arithmetic of numpyh arrays

In [149]:
a1


array([1, 2, 3])

In [150]:
a2

array([[1.3, 2. , 5. ],
       [3. , 5.9, 3. ]])

In [151]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [153]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [154]:
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [156]:
np.add(a1, a2)

array([[2.3, 4. , 8. ],
       [4. , 7.9, 6. ]])

In [157]:
np.multiply(a1, a2)

array([[ 1.3,  4. , 15. ],
       [ 3. , 11.8,  9. ]])

In [162]:
np.remainder(a3, 10)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [163]:
np.log(a2)

array([[0.26236426, 0.69314718, 1.60943791],
       [1.09861229, 1.77495235, 1.09861229]])

## Aggregation
Performing the same operations on a number of things

In [166]:
massive_array = np.random.random(1000)
massive_array[:10]
    

array([0.71992947, 0.48521154, 0.29654095, 0.32745576, 0.92696778,
       0.77735518, 0.32904719, 0.66871484, 0.76931565, 0.18388941])

In [167]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

78.4 µs ± 1.01 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
5.65 µs ± 493 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [168]:
78.4/5.65

13.876106194690266

In [169]:
# Demo for std and var
high_var_array = np.array([1, 100, 300, 500, 1000, 3000])
low_var_array = np.array([2,4,6,8,10])


In [170]:
np.var(high_var_array), np.var(low_var_array)

(1057783.4722222222, 8.0)

In [171]:
np.std(high_var_array), np.std(low_var_array)

(1028.4860097357778, 2.8284271247461903)

In [172]:
np.mean(high_var_array), np.mean(low_var_array)

(816.8333333333334, 6.0)

## Reshaping and Transposing


In [174]:
a2



array([[1.3, 2. , 5. ],
       [3. , 5.9, 3. ]])

In [177]:
a2.shape

(2, 3)

In [176]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [178]:
a3.shape

(2, 3, 3)

In [179]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [183]:
a2_reshape = a2.reshape((2,3,1))

In [184]:
a2_reshape

array([[[1.3],
        [2. ],
        [5. ]],

       [[3. ],
        [5.9],
        [3. ]]])

In [185]:
a2_reshape.shape

(2, 3, 1)

In [186]:
a2_reshape * a3

array([[[ 1.3,  2.6,  3.9],
        [ 8. , 10. , 12. ],
        [35. , 40. , 45. ]],

       [[30. , 33. , 36. ],
        [76.7, 82.6, 88.5],
        [48. , 51. , 54. ]]])

In [187]:
# Transpose 

a2

array([[1.3, 2. , 5. ],
       [3. , 5.9, 3. ]])

In [188]:
a2.shape

(2, 3)

In [189]:
a2.T

array([[1.3, 3. ],
       [2. , 5.9],
       [5. , 3. ]])

In [190]:
a2.T.shape

(3, 2)

## Dot Product vs Element Wise
The man use cases for transposing a matric is `dot product`

In [198]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(3,5))
mat2 = np.random.randint(10, size=(3,5))


In [199]:
mat1

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [200]:
mat2

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0]])

In [202]:
elem_wise_result = mat1 * mat2
elem_wise_result

array([[30,  0, 21, 24,  7],
       [45, 27, 40, 18, 16],
       [21,  0, 24, 40,  0]])

In [210]:
np.dot(mat1, mat2)

ValueError: shapes (3,5) and (3,5) not aligned: 5 (dim 1) != 3 (dim 0)

In [211]:
mat1.T.shape

(5, 3)

In [215]:
mat3 = np.dot(mat1.T, mat2)

In [216]:
mat3

array([[ 96, 116, 128, 156,  41],
       [ 33,  27,  42,  57,  12],
       [ 67,  66,  85, 109,  23],
       [ 52,  39,  61,  82,  11],
       [ 65,  85,  84,  97,  23]])

In [226]:
mat3.shape

(5, 5)

<img src="images/panda.png"/>


In [230]:
# Turn an image into Numpy array
from matplotlib.image import imread
panda = imread("images/panda.png")

In [233]:
panda.shape, panda.ndim, panda.size

((2330, 3500, 3), 3, 24465000)

<img src="images/car-photo.png" />

In [234]:
car = imread("images/car-photo.png")

In [236]:
car.size, car.shape, car.ndim

(991300, (431, 575, 4), 3)

In [238]:
np.unique(car)

array([0.        , 0.00392157, 0.00784314, 0.01176471, 0.01568628,
       0.01960784, 0.02352941, 0.02745098, 0.03137255, 0.03529412,
       0.03921569, 0.04313726, 0.04705882, 0.05098039, 0.05490196,
       0.05882353, 0.0627451 , 0.06666667, 0.07058824, 0.07450981,
       0.07843138, 0.08235294, 0.08627451, 0.09019608, 0.09411765,
       0.09803922, 0.10196079, 0.10588235, 0.10980392, 0.11372549,
       0.11764706, 0.12156863, 0.1254902 , 0.12941177, 0.13333334,
       0.13725491, 0.14117648, 0.14509805, 0.14901961, 0.15294118,
       0.15686275, 0.16078432, 0.16470589, 0.16862746, 0.17254902,
       0.1764706 , 0.18039216, 0.18431373, 0.1882353 , 0.19215687,
       0.19607843, 0.2       , 0.20392157, 0.20784314, 0.21176471,
       0.21568628, 0.21960784, 0.22352941, 0.22745098, 0.23137255,
       0.23529412, 0.23921569, 0.24313726, 0.24705882, 0.2509804 ,
       0.25490198, 0.25882354, 0.2627451 , 0.26666668, 0.27058825,
       0.27450982, 0.2784314 , 0.28235295, 0.28627452, 0.29019